

(define data "(define (display-as-data data)
  (display (integer->char 40))
  (display 'define)
  (display (integer->char 32))
  (display 'data)
  (display (integer->char 32))
  (display (integer->char 34))
  (display data)
  (display (integer->char 34))
  (display (integer->char 41))
  (newline))
(display-as-data data)
(display data)")
(define (display-as-data data)
  (display (integer->char 40))
  (display 'define)
  (display (integer->char 32))
  (display 'data)
  (display (integer->char 32))
  (display (integer->char 34))
  (display data)
  (display (integer->char 34))
  (display (integer->char 41))
  (newline))
(display-as-data data)
(display data)
